services:
    Landlib\SymfonyToolsBundle\Service\FileUploaderService:
        arguments: ["@service_container"]
        class: Landlib\SymfonyToolsBundle\Service\FileUploaderService
        #class: FOS\UserBundle\Controller\GroupController
    